<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue1</name>
   <tag></tag>
   <elementGuidId>70e53ba1-5cf6-49d6-8603-0617baf88b9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#2011 > div.row.margin-top-10 > div.col-xs-12 > #btnNext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id=&quot;btnNext&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47da5bc8-c468-4966-83ae-11b3bfd069d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f370d4e5-ec13-416d-9ef6-07e4d1815e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnNext</value>
      <webElementGuid>f3981d42-c41c-4fca-830a-328376475275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>7d2d6b90-1f90-4c10-bb06-5227abb424ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$.nextQuestionSetStep();</value>
      <webElementGuid>ac7ac283-e0ba-4ae7-9876-ad5d91ad9b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Continue
                            </value>
      <webElementGuid>6424aaee-6cf6-441f-93ff-b584374cc324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2011&quot;)/div[@class=&quot;row margin-top-10&quot;]/div[@class=&quot;col-xs-12&quot;]/button[@id=&quot;btnNext&quot;]</value>
      <webElementGuid>a4840189-cbeb-451c-b58d-b98ebc199124</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='btnNext'])[3]</value>
      <webElementGuid>3e53f3cb-1d88-4dfb-8812-588f013de1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2011']/div/div/button[2]</value>
      <webElementGuid>b0fdfa59-7331-4f5b-9ed9-7c116e0a9d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[3]/following::button[1]</value>
      <webElementGuid>3cd2b2af-e85b-45a9-9355-b5ce0e2427c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How many years does the honorary membership last?'])[1]/following::button[2]</value>
      <webElementGuid>6bd24dfc-8cbf-4926-b236-b5c361f5ac82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Progress'])[1]/preceding::button[1]</value>
      <webElementGuid>767d386e-f9ea-4395-af12-815ff35577bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::button[1]</value>
      <webElementGuid>36a20ac6-ede9-4d2e-8078-245e418a239f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button[2]</value>
      <webElementGuid>c0af5579-cd01-4d1f-b94e-8c22e832ba62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
