<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Does the above fee include Toastmasters membership dues_MainQuestions4.Answer</name>
   <tag></tag>
   <elementGuidId>d532a081-4d6d-43b3-be70-7444a46041a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MainQuestions_4__Answer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57e64102-d00e-4003-89de-4c7fc1363689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radioYesNo</value>
      <webElementGuid>57223f9a-07fa-4fd0-90db-fa1cd200ac49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-questionsetid</name>
      <type>Main</type>
      <value>2019</value>
      <webElementGuid>bd7156db-fe36-45be-b4a3-e67d24c250fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MainQuestions_4__Answer</value>
      <webElementGuid>1167d5cf-9f34-4810-9e0f-73ff7d1e3f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MainQuestions[4].Answer</value>
      <webElementGuid>270c7fa7-2b81-4bfa-b15b-5b208884603c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3aa20ece-5b90-4c81-94dc-fa030696b80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>de30eb0c-18ad-4aa3-b969-31d4082f3094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2018&quot;)/form[@id=&quot;mainForm&quot;]/div[@class=&quot;row margin-top-5 question&quot;]/div[@class=&quot;col-xs-12 col-sm-10 noLeftPadding&quot;]/div[@class=&quot;form-group&quot;]/p[2]/input[@id=&quot;MainQuestions_4__Answer&quot;]</value>
      <webElementGuid>c93c0a9a-3775-4c8b-9c6b-da887fca969e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MainQuestions_4__Answer']</value>
      <webElementGuid>e5723ab2-36c3-42ed-89df-5338b32715ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainForm']/div[2]/div[2]/div/p[2]/input</value>
      <webElementGuid>0c7ff62d-6cfb-4505-a669-f9a56774420c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/input</value>
      <webElementGuid>bb1eebdd-0622-4564-bf76-f26f91af0311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html/body/div[1]/main/div[1]/div[5]/div[2]/div[4]/form/div[2]/div[2]/div/p[2]/input[1]</value>
      <webElementGuid>76e8cb05-2d7f-4178-8852-5365b20dacab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
