<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_PopupAddToCartBtn</name>
   <tag></tag>
   <elementGuidId>c847e4d7-b6cb-4f06-b4f7-cdc3bd4d563d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='AddToCartButtonPage_a539ef3a-8cd7-ec11-a2fd-005056875f20']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
