<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_EnterRenewalPeriod</name>
   <tag></tag>
   <elementGuidId>f4f965e6-d25a-4e2d-857c-6dc529a95275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@data-id='a539ef3a-8cd7-ec11-a2fd-005056875f20'])[7]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
