<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_SelectRenewalType</name>
   <tag></tag>
   <elementGuidId>d993a26a-e3ec-4656-b5c1-b8cb6a0a5564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='RenewAndReinstate_a539ef3a-8cd7-ec11-a2fd-005056875f20']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
