<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_ClickOnRenewalPeriod</name>
   <tag></tag>
   <elementGuidId>2587e020-11d5-4503-9eb5-2be904d27b28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='RenewMemberTerms_a539ef3a-8cd7-ec11-a2fd-005056875f20']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
