<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_ratingStart_qualities_of_Fellowship_Variety_Communication</name>
   <tag></tag>
   <elementGuidId>ec3d4eac-dded-4648-b169-1fbf6cea9d6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//form[@id='mainForm']/div/div[2]/div/div[2]/p/span/i[5])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ratingStar star-border-notselected fa fa-star-o fa-2x</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1019&quot;)/form[@id=&quot;mainForm&quot;]/div[@class=&quot;row margin-top-5&quot;]/div[@class=&quot;col-xs-12 col-sm-10&quot;]/div[@class=&quot;form-group main-question-body question-required&quot;]/div[@class=&quot;row margin-top-3&quot;]/p[@class=&quot;margin-left-15&quot;]/span[@class=&quot;text-warning&quot;]/i[@class=&quot;ratingStar star-border-notselected fa fa-star-o fa-2x&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='mainForm']/div/div[2]/div/div[2]/p/span/i[5])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/div/div[2]/div/div[2]/p/span/i[5]</value>
   </webElementXpaths>
</WebElementEntity>
