<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_English</name>
   <tag></tag>
   <elementGuidId>55dfb1ce-5ed8-4247-bf40-fc290636c9b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[contains(text(),'English')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
