<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ClubOfficerForFirstOption</name>
   <tag></tag>
   <elementGuidId>efa46c7c-e68b-4bc2-ae28-ddab9f951e30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmPathwaysAward&quot;]/div[1]/section[3]/div[2]/div/div/div[1]/div/ul/li[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
