<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ClubOfficerRoleForFirstOption</name>
   <tag></tag>
   <elementGuidId>b4d92b5c-9d24-48df-99ab-9ff22b913bfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmPathwaysAward&quot;]/div[1]/section[3]/div[2]/div/div/div[1]/div/ul/li[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
