<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ClubOfficerRoleCompletion</name>
   <tag></tag>
   <elementGuidId>58846e2c-5770-4da0-afd3-f2cc298cfb0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-id=&quot;ddlPromptClubOfficerRoleCompletionClubLeaderships&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
