<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Object1</name>
   <tag></tag>
   <elementGuidId>1ef6058f-af56-4c45-8966-d24464fd5c16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ifarme[@id=&quot;Microsoft_Omnichannel_LCWidget_Chat_Iframe_Window]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
