<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Standard  15 Express Handling - 24.25_2b7d76</name>
   <tag></tag>
   <elementGuidId>72392d25-af00-4e0f-bf41-99a343edba6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;2DAYEXPRESS&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>787ea569-20c1-4126-abcb-35b794cf2b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d1df7158-0cc5-42dc-b026-e1b4ce887050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shippingOption</value>
      <webElementGuid>8abf6865-5c62-4daf-be61-bad3dcbf72ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabbable ng-pristine ng-valid</value>
      <webElementGuid>6c4ef0b4-35c9-4583-9b93-42d29268780c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$parent.selectedOption</value>
      <webElementGuid>41dddba1-68ec-49af-9e58-1738175c0cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-value</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c19f489c-4c67-40d3-8c7b-f7a630a7c9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>disableOptionForExpress(option)</value>
      <webElementGuid>4543d45f-23d9-4c39-bb14-8b3f89e9f576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2 Day + $15 Express Handling</value>
      <webElementGuid>69e955eb-82ae-4247-b11f-e36ec4da0f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>9e6a854c-2dba-4d98-a59e-c5bf0bf04d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2 Day + $15 Express Handling&quot;)</value>
      <webElementGuid>cea5df08-4ac7-4dc5-a77a-33218d5fe6b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='2 Day + $15 Express Handling']</value>
      <webElementGuid>e9210681-6df4-4df7-9bf0-2e962c70747e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/div[3]/div[2]/div/div[3]/label[5]/input</value>
      <webElementGuid>ff403f7f-369f-4faa-9ef7-74dc6c278dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[5]/input</value>
      <webElementGuid>9ac4cdd1-8029-47f2-b186-8bcfd3610829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'shippingOption' and @id = '2 Day + $15 Express Handling']</value>
      <webElementGuid>7510d4b5-72e5-461c-8294-efb8b4eb118f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
