<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Standard - 9.25_shippingOption_1_2</name>
   <tag></tag>
   <elementGuidId>87928b6c-20c2-4cd2-8f58-f687d7bc4ac9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;STDEXPRESS&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea720a6e-0f83-4113-a0b8-9a21736706b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0a4e12be-b4b3-4889-bc4a-ea7409015c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shippingOption</value>
      <webElementGuid>861b876c-2996-4e6f-b00f-98ed71f113c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabbable ng-pristine ng-valid</value>
      <webElementGuid>617b1166-6d68-4fcb-a46c-a3e38f7f2bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$parent.selectedOption</value>
      <webElementGuid>d4d9e4b4-ff0a-4668-b47d-b1b638b4ba8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-value</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f910cf06-1ba6-4260-b6c9-0da003b7a74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>disableOptionForExpress(option)</value>
      <webElementGuid>ddfbc472-4361-4ed6-a676-22ea7b7fedff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Standard + $15 Express Handling</value>
      <webElementGuid>29aeca96-5e4c-481b-a430-ba624f37da20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>9f1144fc-e7a0-4cd4-9d1c-b68902b05c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Standard + $15 Express Handling&quot;)</value>
      <webElementGuid>b1c45f19-1c7e-4648-87cb-5cb9c33bb9e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Standard + $15 Express Handling']</value>
      <webElementGuid>1c6629b3-d2a0-4d27-acb1-fcb905c54953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/div[3]/div[2]/div/div[3]/label[4]/input</value>
      <webElementGuid>075a2e47-b537-4782-91c1-fe66bbc5cc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/input</value>
      <webElementGuid>a657fa73-e619-4507-bc28-8d94cef85c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'shippingOption' and @id = 'Standard + $15 Express Handling']</value>
      <webElementGuid>a0795122-7e9c-4238-a3dc-f4de206e7420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
