<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Update</name>
   <tag></tag>
   <elementGuidId>cf9f54c0-dbf5-479a-88b3-68566ddf0f94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.update-product.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@ng-click=&quot;updateProductExtended(product)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c5a4006a-9cdf-4a98-8dd9-2e25890200f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>update-product ng-scope</value>
      <webElementGuid>a681c8cc-e89e-475d-bbd2-674fdc7ac9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>updateProductExtended(product)</value>
      <webElementGuid>b2afd139-0041-479a-822a-e619b8631ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>isQuantityDirty</value>
      <webElementGuid>cd827ff9-57b3-4f3c-aa9b-33082918c2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>6a77299c-d1cc-4bc0-9f37-7775b9def67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products-list&quot;)/tbody[@class=&quot;ng-scope&quot;]/tr[2]/td[3]/p[@class=&quot;text-right actions&quot;]/a[@class=&quot;update-product ng-scope&quot;]</value>
      <webElementGuid>b8b8a90a-6fee-4b1b-91d4-d3ce1c173ed7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='products-list']/tbody/tr[2]/td[3]/p/a</value>
      <webElementGuid>659e8ef8-10d8-4483-8147-cfc76b19fb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Update')])[2]</value>
      <webElementGuid>9507403f-c55f-49e4-a59e-afd3786c5db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/following::a[1]</value>
      <webElementGuid>be8fe5d7-e5a6-43c3-b1d7-5eb20f63721d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Engraving'])[1]/following::a[1]</value>
      <webElementGuid>591ddf02-8a8e-4a13-8a46-316099b3b1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove All'])[1]/preceding::a[1]</value>
      <webElementGuid>c0089f22-d6b0-4d03-9adf-49b8b58a0ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[1]/preceding::a[2]</value>
      <webElementGuid>e6074378-abc9-49bf-8562-2d5fa05ecbf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update']/parent::*</value>
      <webElementGuid>d881d265-eeeb-4d2b-9bdb-11ce6b49bac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/p/a</value>
      <webElementGuid>764ccbe0-b49f-4002-b4e8-49edaa7ae2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Update' or . = 'Update')]</value>
      <webElementGuid>f2c4a798-bf07-402f-93bd-8c0125c9987f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
