<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Promo Code_coupon-enter</name>
   <tag></tag>
   <elementGuidId>e0d6b3dd-8ac7-4533-960d-21568a6f613e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coupon-enter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='coupon-enter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d08df0f-30f4-42c9-801a-7d933c6b7dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>cart.Coupon || false</value>
      <webElementGuid>b68247e8-7778-4e45-8573-34688813f918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>newCoupon.Code</value>
      <webElementGuid>211216a0-313d-422d-8bf6-a3b577870070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ac-enter</name>
      <type>Main</type>
      <value>applyCouponExtended()</value>
      <webElementGuid>d8f9917e-03e4-43c3-ad3d-903350606742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coupon-enter</value>
      <webElementGuid>257e4ec0-fbc1-4e6a-9a13-48bd4070f6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>has-default ng-pristine ng-valid</value>
      <webElementGuid>769c8bc4-7e61-4066-9e33-e686bb12a942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7161ce6-c79c-4fd4-87d0-99c721dc478c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>636007fb-e07e-4457-82d1-c84c42784d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Promo code</value>
      <webElementGuid>8e6f2557-4253-4ebf-a988-18a046654057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coupon-enter&quot;)</value>
      <webElementGuid>c619a06c-d774-4c0e-ae0d-4d3c85869d60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coupon-enter']</value>
      <webElementGuid>d50662fb-9a77-433d-af32-6224adf94d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-coupon']/div/input</value>
      <webElementGuid>e07fd1df-1dee-49ab-b537-1cfffb852b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>a1a25bc2-c2e5-4edc-b2d5-f02004aadd95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'coupon-enter' and @type = 'text']</value>
      <webElementGuid>7af00d6f-1d41-4cec-bf55-9dcef634dde2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
