<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_36.00</name>
   <tag></tag>
   <elementGuidId>5b68d2b6-128a-4d6e-afd8-47e1b4334c73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.shoppingCartAmtSpan.ng-binding.discount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='products-list']/tbody/tr/td[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>74b31882-bf1c-41ee-8f7b-fb9470da9163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shoppingCartAmtSpan ng-binding discount</value>
      <webElementGuid>b3299b50-32c0-464b-987c-4f7177109927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{discount: product.WasPrice}</value>
      <webElementGuid>800c91b3-56be-4451-b3fe-e1d1215a41fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$36.00</value>
      <webElementGuid>596762a2-dc4d-4c35-8cd3-4338690dddd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products-list&quot;)/tbody[@class=&quot;ng-scope&quot;]/tr[1]/td[@class=&quot;amt&quot;]/span[@class=&quot;shoppingCartAmtSpan ng-binding discount&quot;]</value>
      <webElementGuid>c48c23ae-5d32-4ffb-8610-6362afcb9142</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='products-list']/tbody/tr/td[4]/span</value>
      <webElementGuid>f12f71c8-f438-4794-8d69-eba68fad5d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Out of stock'])[1]/following::span[1]</value>
      <webElementGuid>6e96e027-0c0a-42d8-9f8d-21ab8d729886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/following::span[1]</value>
      <webElementGuid>7ff0503f-33c0-4ba6-ae52-aa603cd5f00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Engraving'])[1]/preceding::span[1]</value>
      <webElementGuid>eb3fbfc9-05de-40a4-952b-e76af03e5f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/preceding::span[1]</value>
      <webElementGuid>acd37706-fcf5-473a-9eb5-773ddf7260a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$36.00']/parent::*</value>
      <webElementGuid>4b9f5f2e-bb12-4ea1-ba46-388160f12b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/span</value>
      <webElementGuid>1a28430f-4b8f-4ea9-a3c6-b80f5994e422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$36.00' or . = '$36.00')]</value>
      <webElementGuid>05779e8f-84e4-442e-a125-b24c6c83a545</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
