<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Email</name>
   <tag></tag>
   <elementGuidId>f2ee3cd7-6ecc-4bb5-b6b7-5a314a19317f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//h4[contains(text(),'Email')])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
