<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add to Cart_ViewDetailsPage (1)</name>
   <tag></tag>
   <elementGuidId>03a30492-7545-4e4c-8833-d0a3a1fb2429</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnAddToCart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnAddToCart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36a80be5-390f-4618-af6d-fc3df86dd965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddToCart</value>
      <webElementGuid>68df57f8-37dd-416b-a5c5-403098e74b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>8bd15470-2b89-4421-aa78-82f56d113fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>/ac/cart/AddToCart/B63</value>
      <webElementGuid>ee2218f9-c00e-43e1-b83f-ad9903c57e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>marbot10 add-to-cart bttn bttn-primary bttn-block causes-validation </value>
      <webElementGuid>a428e770-cc6a-4b2f-82cc-fe72b7a658c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-id</name>
      <type>Main</type>
      <value>B63~Personally Speaking</value>
      <webElementGuid>87911700-4e30-475a-af2b-93f08a6e5bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-category</name>
      <type>Main</type>
      <value>ActiveCommerce-ProductDetail</value>
      <webElementGuid>a3150ac5-a45a-4a9d-af4a-742f764d66fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-waittext</name>
      <type>Main</type>
      <value>Adding...</value>
      <webElementGuid>4460ad46-e54f-42b8-83b8-f819a89c5b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ Add to Cart</value>
      <webElementGuid>33b8416b-a452-4195-bfe4-7b9861c54d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddToCart&quot;)</value>
      <webElementGuid>3d9db8f2-c1b7-4682-b252-87b47e33d7be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnAddToCart']</value>
      <webElementGuid>55acdc11-a51c-48c8-9f4b-b413e4294775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='btn-add-to-cart']/div[2]/a</value>
      <webElementGuid>da3a5bd7-15a1-4eab-b802-121e0b883560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'+ Add to Cart')]</value>
      <webElementGuid>82cbfb9e-403a-4f65-9e12-199872239612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Weight: 0.563 lbs'])[1]/following::a[2]</value>
      <webElementGuid>253b4f4d-5798-4ea3-ada8-c95afadb6fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member Price: $7.50'])[1]/following::a[2]</value>
      <webElementGuid>0d9c179d-9e12-40a5-b6a2-7812ebe1d230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::a[1]</value>
      <webElementGuid>2cf92cff-bdb3-402c-a9d4-77762d88ec69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Cart + Checkout'])[1]/preceding::a[6]</value>
      <webElementGuid>4446e34d-820f-4b16-9581-87c27e4bea9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+ Add to Cart']/parent::*</value>
      <webElementGuid>79dfb6b0-4466-435a-ac21-f1075589dd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>23bedaa3-c9eb-4eae-9d7a-586ddc180749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>980d8d8b-da3e-46e9-bed3-207cdeda6803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnAddToCart' and @href = 'javascript:void(0)' and (text() = '+ Add to Cart' or . = '+ Add to Cart')]</value>
      <webElementGuid>258d3019-773c-40f7-8dd7-1f38dd50b274</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
