<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add To Cart_On_ViewProductListingPage_PopUp</name>
   <tag></tag>
   <elementGuidId>e317214a-dd3d-4077-a54c-b355f0042d9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;addToCart();&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>7792cfb9-2d93-458d-b7ee-b7898759336f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1661147760518</value>
      <webElementGuid>423602d7-3e3d-467c-b816-a6dd9f83b7fc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
