<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add to Cart_ViewDetailsPage</name>
   <tag></tag>
   <elementGuidId>65a88a79-e1a2-45ea-9072-d9d1fdf278c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnAddToCart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnAddToCart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b8ac0ed6-ffc1-4710-9a43-a140474b4cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddToCart</value>
      <webElementGuid>485f5c50-7899-4e3a-829d-ef7005a88fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>f95dd052-9d58-40d7-800d-bc0c7b7fe23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>/ac/cart/AddToCart/B1</value>
      <webElementGuid>67eedb2b-47d2-4001-9691-419c036fbbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>marbot10 add-to-cart bttn bttn-primary bttn-block causes-validation </value>
      <webElementGuid>bd5ea303-0234-4130-a5a7-0d3bc223b01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-id</name>
      <type>Main</type>
      <value>B1~The Story of Toastmasters</value>
      <webElementGuid>cc6a2860-7427-4e62-b3c7-b508f3fed534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-category</name>
      <type>Main</type>
      <value>ActiveCommerce-ProductDetail</value>
      <webElementGuid>92f58125-a34b-4104-8538-6090ca1d71b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-waittext</name>
      <type>Main</type>
      <value>Adding...</value>
      <webElementGuid>1bf26ab0-223b-42ee-8391-cff5e3f7ba4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ Add to Cart</value>
      <webElementGuid>ddfda87f-67ce-4dc5-b89a-4afd799ac0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddToCart&quot;)</value>
      <webElementGuid>9a3f557c-8b7c-4c00-b4e6-93580523e695</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnAddToCart']</value>
      <webElementGuid>cb627659-de45-4bde-a3f3-a310f64ab5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='btn-add-to-cart']/div[2]/a</value>
      <webElementGuid>a6ae3217-fedc-4d35-abfe-f40a7d0b2ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'+ Add to Cart')]</value>
      <webElementGuid>578da5ac-122a-4576-8682-d2c5eb8f9073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Weight: 0.375 lbs'])[1]/following::a[2]</value>
      <webElementGuid>1a2e3f3e-8e43-4381-b15b-ae7915b75cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member Price: $7.50'])[1]/following::a[2]</value>
      <webElementGuid>dfe38649-f051-4b3d-9a72-acdb4e284f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::a[1]</value>
      <webElementGuid>66989053-6ef8-4dd9-a0d9-66a4e3977a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Story of Toastmasters'])[3]/preceding::a[6]</value>
      <webElementGuid>e796cdf6-2972-4d0e-b1d8-0b506753e316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+ Add to Cart']/parent::*</value>
      <webElementGuid>e8ca8b68-59fb-4e79-94a6-e8d1b2fed3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>18f2d3a8-fd92-4c15-aa95-9f5c71e67cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>be911efa-cf2e-4123-9b35-4bc4d2e09dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnAddToCart' and @href = 'javascript:void(0)' and (text() = '+ Add to Cart' or . = '+ Add to Cart')]</value>
      <webElementGuid>967d4ca3-775e-46d0-bdf4-c4a580390dc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
