<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Books</name>
   <tag></tag>
   <elementGuidId>23b87477-0379-4071-9ea8-e0c3abe4e0b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EducationPane']/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>215bb853-fed7-4190-8902-37dedb301a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/shop/education/books</value>
      <webElementGuid>ced2e0c6-3bde-40fb-9424-879c62e23585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Books</value>
      <webElementGuid>5b109743-2e11-4043-b370-eb01abd02086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EducationPane&quot;)/div[@class=&quot;row&quot;]/ul[@class=&quot;column&quot;]/li[2]/a[1]</value>
      <webElementGuid>37f74a66-2b9b-4ca6-abd7-6f5f79008835</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EducationPane']/div/ul/li[2]/a</value>
      <webElementGuid>2c531ce0-7c42-46e9-a541-cb20ac295c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Books')])[2]</value>
      <webElementGuid>50ca4e3e-bdd8-4419-92e4-02b00589524a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manuals'])[2]/following::a[1]</value>
      <webElementGuid>6564ed05-017e-4cb6-bdb9-303a530878cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gifts'])[3]/following::a[2]</value>
      <webElementGuid>1d663d01-f1e7-41ab-865e-51fbfc3452a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programs and Modules'])[2]/preceding::a[1]</value>
      <webElementGuid>9b9b8070-e92b-4678-bce2-1e347f4019eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Translated Materials'])[2]/preceding::a[2]</value>
      <webElementGuid>ca08f3d9-7c9f-44a3-8d2e-2488a205f7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/shop/education/books')])[2]</value>
      <webElementGuid>5159e51e-1695-42f7-99b5-594e89e14179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li[2]/a</value>
      <webElementGuid>0791ee14-ebb2-4942-a7de-991919a9b47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/shop/education/books' and (text() = 'Books' or . = 'Books')]</value>
      <webElementGuid>97ecb6a9-e003-4f31-8bec-cd557a6b78d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
