<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_close_ProductListingPage</name>
   <tag></tag>
   <elementGuidId>c0376735-6109-4ed5-97c4-14e8d9ba1867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#added-to-cart-close-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick=&quot;hideAddedToCart();&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bf883ee0-1abf-4a4b-b675-18de67050d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>b6fd976f-ed50-4476-a635-ab129b3aa187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>added-to-cart-close-button</value>
      <webElementGuid>324a8ce7-cf5b-44ee-ba0f-582c81fe38cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>071322e2-695b-4ead-befe-5083db8b4ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hideAddedToCart();</value>
      <webElementGuid>40b79b95-2ba5-4cd0-b018-81331f755817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>512e1606-fcc5-417c-95b5-20a3b43dcc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;added-to-cart-close-button&quot;)</value>
      <webElementGuid>a9d18f20-51a6-4549-a835-1efee987c3fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='added-to-cart-close-button']</value>
      <webElementGuid>9c3077e1-1611-459a-be5a-823ae6f72703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='added-to-cart']/a</value>
      <webElementGuid>9cdc53f6-003d-4f6e-8f1b-c252d3ae3846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'close')]</value>
      <webElementGuid>a80d4352-aa1e-492f-8d25-410ce2b38adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Translated Materials'])[3]/following::a[1]</value>
      <webElementGuid>1cf9980a-b166-44fe-8362-94c0aaf47f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Youth Programs'])[1]/following::a[2]</value>
      <webElementGuid>87560093-6208-4ab4-af3d-919969c8734c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Story of Toastmasters, Vol. II'])[1]/preceding::a[1]</value>
      <webElementGuid>894aa7ef-3066-4eec-8e3b-db1942c8c1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity: 1'])[1]/preceding::a[1]</value>
      <webElementGuid>51e6811b-1980-4fe9-a302-858129aa342b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='close']/parent::*</value>
      <webElementGuid>08bc6f1d-f1fa-4699-8504-62ed275b2a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>9e7080f1-898c-4775-a800-19a5414de7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>091066de-0fd5-4056-85ca-3e0ba22bf058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'added-to-cart-close-button' and @href = 'javascript:void(0);' and (text() = 'close' or . = 'close')]</value>
      <webElementGuid>7dab095b-d0d7-4ef8-9348-d5f41011fd89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
