<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>292d0a9d-4336-46d9-b70b-80dbb0793556</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnGo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnGo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a0a9541-1687-459e-88d9-2bac1ea7a7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnGo</value>
      <webElementGuid>e5d3b00d-dced-46d2-9a7f-a5f1b5f3c76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnSearch_Shop</value>
      <webElementGuid>ee0f62ed-0798-4cf4-9a77-e768ab2b9900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f4151f73-4fb5-46fc-a6da-08c8b090c761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>search()</value>
      <webElementGuid>a1f2ea9a-81d3-433b-80bd-9b8ad477655e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	                                
	                                Search
                                </value>
      <webElementGuid>29ff7d52-b804-48cd-a40c-5ede303858d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnGo&quot;)</value>
      <webElementGuid>7bf8ea18-18a2-4c23-9af6-7641280dc140</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnGo']</value>
      <webElementGuid>2100e566-2f30-432b-a017-d5d693204547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ctl00']/section/div/div/div[2]/div/div/div/div/button</value>
      <webElementGuid>6c14a06f-c6a4-47b4-b124-a0a4ed0a63be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse Products:'])[1]/following::button[1]</value>
      <webElementGuid>f82d7833-ae5e-46c1-8868-12ed9fe7c4e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHOP NOW'])[3]/following::button[1]</value>
      <webElementGuid>8e7a276a-a75f-4b15-932f-9d5fa70c625a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For You'])[1]/preceding::button[1]</value>
      <webElementGuid>00758903-2d1b-4163-9f57-fe5be8c7b0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>0976629d-47f3-4f54-bf8e-45201cc24d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnGo' and @type = 'button' and (text() = '
	                                
	                                Search
                                ' or . = '
	                                
	                                Search
                                ')]</value>
      <webElementGuid>79cbecd6-af77-46a4-85f1-c1a0dc4525b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
