<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Backordered</name>
   <tag></tag>
   <elementGuidId>77642910-7684-44a5-a977-26b3569a3881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = 'Backordered' or . = 'Backordered')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>035841e5-9bd6-4e02-9f7a-673714a24eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-validation</value>
      <webElementGuid>e251028e-7753-461f-bf97-77b1b8f5356c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Backordered</value>
      <webElementGuid>c52bbdf7-6b06-489c-8b32-629fd5a5c35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;added-to-cart&quot;)/div[@class=&quot;added-product&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;description&quot;]/div[@class=&quot;infobox-val&quot;]/p[@class=&quot;label-validation&quot;]</value>
      <webElementGuid>836d7dbe-b575-4f36-84de-03528f6b1512</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='added-to-cart']/div/table/tbody/tr/td[2]/div/p[5]</value>
      <webElementGuid>56237e65-c3ac-4813-961e-4ac8dafc7108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Story of Toastmasters'])[3]/following::p[5]</value>
      <webElementGuid>99c19eda-a2f4-4065-a166-ea27b78de232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::p[7]</value>
      <webElementGuid>54b28a7e-e789-4e21-90e9-ab70ca1d3e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtotal'])[1]/preceding::p[1]</value>
      <webElementGuid>5352a4e1-e523-4e3d-b056-c06f266e0c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Backordered']/parent::*</value>
      <webElementGuid>d0e9a106-374c-4966-b828-417d7396e63c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]</value>
      <webElementGuid>a90c43f8-70d3-441c-80a1-2edafe0c9a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Backordered' or . = 'Backordered')]</value>
      <webElementGuid>4ab1db3f-919b-4846-b3bc-ae8a71e0e746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
