<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LastTimeconMOT</name>
   <tag></tag>
   <elementGuidId>27f31d78-cbf9-4b95-af93-78f54213a544</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='singleLineTxtAnswer_765eb926-d437-4b03-a912-9a1c975ebf00']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
