<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_EduEnga1</name>
   <tag></tag>
   <elementGuidId>cd12f6e0-5c45-4dbf-ad10-86f0009ca725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtAnswer_bfc580ce-552e-4b78-9b08-ebb04dc8c915']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
