<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_StatAndTactEdu2</name>
   <tag></tag>
   <elementGuidId>5d4a504f-ecbc-4c7a-a266-6c92ee100372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtAnswer_f650c5e6-ca25-4927-bee3-9d5e3b6d226b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
