<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mobile Phone_iti-arrow</name>
   <tag></tag>
   <elementGuidId>3b5ce7fb-9b0e-4e19-a5ed-1189ab0df336</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;divMobile&quot;]//div//div[@class=&quot;selected-flag&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.iti-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34ba9338-29ad-42d2-8d77-7a2f4e97fe82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti-arrow</value>
      <webElementGuid>c10b81b5-642b-4ef1-8494-11f92d14ea2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMobile&quot;)/div[@class=&quot;intl-tel-input allow-dropdown&quot;]/div[@class=&quot;flag-container&quot;]/div[@class=&quot;selected-flag&quot;]/div[@class=&quot;iti-arrow&quot;]</value>
      <webElementGuid>e0237144-6907-4043-a1fd-001e05cbd7fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMobile']/div/div/div/div[2]</value>
      <webElementGuid>4df41c0d-04e7-4815-bb98-3a148ace995a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]</value>
      <webElementGuid>bd581d2c-a964-4eba-9bb7-389f77141f03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
