<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_ExpiryYear</name>
   <tag></tag>
   <elementGuidId>b93c33a2-97a1-43e6-9e6b-0d3063dfdfad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[@value=&quot;2024&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
