<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_QualifyingRequiremt</name>
   <tag></tag>
   <elementGuidId>129627ab-671c-4a47-8b1b-94f61bce09dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='singleLineTxtAnswer_08b2e97e-4d02-44c1-a43c-9575fdac5b3b']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
