<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_ValidationCreditcardNumber</name>
   <tag></tag>
   <elementGuidId>e18d1bae-f229-4dab-a3bb-e579b0622efc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/main/div[3]/div[10]/form/div[1]/div[4]/div[1]/div/ul/li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
