<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Accepted (0 vote)</name>
   <tag></tag>
   <elementGuidId>44007a0f-c0dd-4e6c-a64c-89013bd48db1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AcceptedCollapse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='AcceptedCollapse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bd18cb3a-217d-4314-b8ba-42503f72b2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>74c2002b-ea76-4bd1-9755-55e6c3eaa916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AcceptedCollapse</value>
      <webElementGuid>f7b55a5f-a773-4eb1-aea2-52c5e0ba680a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordionmyproxy</value>
      <webElementGuid>f0c1c3c6-746c-45d6-8b97-cb7ec049bec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#collapseAccepted</value>
      <webElementGuid>3e7bf22b-c205-4912-8122-c928dac9d572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a0ea4e99-17ab-43d5-bee1-b748ac7eaa3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsed</value>
      <webElementGuid>17feba47-2998-460c-9477-7a9d2f4e193b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accepted (0 vote)</value>
      <webElementGuid>a6f77dac-2c64-4e59-8776-80f773e41f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AcceptedCollapse&quot;)</value>
      <webElementGuid>8550ee85-2b3a-4e77-bab1-5793df58220c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='AcceptedCollapse']</value>
      <webElementGuid>eff6bf90-08ee-42a0-b91a-521edd6478cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionmyproxy']/div[2]/div/h4/a</value>
      <webElementGuid>9560200a-b3cb-427b-ad9b-52e762560da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tuesday, August 16, 2022'])[1]/following::a[2]</value>
      <webElementGuid>bf9d2b60-c3ba-4791-9634-62736d1e6425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saturday, August 13, 2022'])[1]/following::a[2]</value>
      <webElementGuid>b9e1c7eb-8746-4305-b827-d0cd1fcbdd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saturday, August 13, 2022'])[2]/preceding::a[1]</value>
      <webElementGuid>0cc3d88d-4a1f-4de7-a980-a955264ae862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accepted']/parent::*</value>
      <webElementGuid>d72fd69e-fe3c-4a59-b387-79c5ab83f04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#collapseAccepted')]</value>
      <webElementGuid>47fb0d06-a354-47ed-a5b3-ffa99a580f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/a</value>
      <webElementGuid>056ebf14-56bf-4994-aecd-bd1476daabe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'AcceptedCollapse' and @href = '#collapseAccepted' and (text() = 'Accepted (0 vote)' or . = 'Accepted (0 vote)')]</value>
      <webElementGuid>3f7bfd3c-9eb5-469a-8187-d6a36435796e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
