<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_International Directors (click to expand)</name>
   <tag></tag>
   <elementGuidId>541a9536-50f0-47f0-a89a-02e1228fcde6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DirectorCollapse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectorCollapse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>22c0c81b-602f-4742-a965-e15c4d032408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>7a3c93c6-fc1a-4725-aefd-49f187d68732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectorCollapse</value>
      <webElementGuid>96cded9b-433e-4118-9e0e-b8effa54d510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordionassign</value>
      <webElementGuid>3b94fa65-d464-4818-8ce4-5e6e8a1cccb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#collapseDirectors</value>
      <webElementGuid>383f5162-654c-4492-b0a4-ec2b3d9d7c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ef2db78c-d097-4bd2-bf74-ad01147fc172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>International Directors (click to expand)</value>
      <webElementGuid>c8f2b353-17f0-458a-a2e8-e6be74a37efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectorCollapse&quot;)</value>
      <webElementGuid>2f2aabb8-0329-4ba0-b4f3-7a05057b6be3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectorCollapse']</value>
      <webElementGuid>74f498e0-8cca-4eed-8e5b-34ae1f831ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionassign']/div[2]/div/h3/a</value>
      <webElementGuid>3a601e81-dcf6-45ed-a569-140ac5e83438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'International Directors (click to expand)')]</value>
      <webElementGuid>5af3f53d-37be-4343-9c52-1aa88928063d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Second Vice President'])[1]/following::a[3]</value>
      <webElementGuid>1409dfb8-9c29-48b5-820c-bc7ddc287f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Vice President'])[1]/following::a[4]</value>
      <webElementGuid>bccdcd1b-68b4-4875-8260-d76b55877cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region 2'])[1]/preceding::a[1]</value>
      <webElementGuid>44e042ff-06d8-42cf-8bcf-f52d84b14670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region 4'])[1]/preceding::a[3]</value>
      <webElementGuid>20c2114d-1912-4aed-ac71-357dde2f5e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='International Directors (click to expand)']/parent::*</value>
      <webElementGuid>03c9b2a1-eb7e-40cd-91f1-3a2810c380ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#collapseDirectors')]</value>
      <webElementGuid>074d8aec-f1eb-4f28-89bc-f4fa81c59308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h3/a</value>
      <webElementGuid>d22e215f-8561-4586-be41-ea9a39cc1a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectorCollapse' and @href = '#collapseDirectors' and (text() = 'International Directors (click to expand)' or . = 'International Directors (click to expand)')]</value>
      <webElementGuid>badbc535-3ea7-45ee-a81c-e4066b0fa866</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
