<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_International Officers (click to expand)</name>
   <tag></tag>
   <elementGuidId>c8575c96-2809-4085-a866-f61f58d66116</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OfficerCollapse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='OfficerCollapse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2e36d08b-8514-4b47-b34e-b54f5fa83c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>cd494c35-0755-4a5b-9f62-3b2b296aee8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OfficerCollapse</value>
      <webElementGuid>f24f9d99-9a53-42f4-b92a-6486a42ce1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordionassign</value>
      <webElementGuid>3bcc2c78-d8a4-469b-b527-8127a9b18c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#collapseOfficers</value>
      <webElementGuid>d8c1e120-9aa1-4a46-b4d2-555063d9049a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8c0da496-e6bf-4537-8045-7d157d7141a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>International Officers (click to expand)</value>
      <webElementGuid>e231689b-f55d-418e-a178-fe93787ca239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OfficerCollapse&quot;)</value>
      <webElementGuid>385ce415-b139-4757-9dcb-54ebea1b9a90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='OfficerCollapse']</value>
      <webElementGuid>149ea540-8a36-4669-8f22-acacb12bdab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionassign']/div/div/h2/a</value>
      <webElementGuid>dbaa6883-fcfb-44b8-82cb-c5a142c55f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'International Officers (click to expand)')]</value>
      <webElementGuid>d58a5f2a-b48c-4cb7-9004-d09b52b4ea02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proxy Acceptance Recorded'])[3]/following::a[2]</value>
      <webElementGuid>ed7817d3-db5e-44fe-ba35-e943d230dc0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return votes'])[2]/following::a[2]</value>
      <webElementGuid>3f55c815-5732-425a-8e20-96a53c1fda88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='International President-Elect'])[1]/preceding::a[1]</value>
      <webElementGuid>8243a715-05e5-4995-ab0f-24e39bc01ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Vice President'])[1]/preceding::a[2]</value>
      <webElementGuid>558b1679-71c3-46e1-ba4c-f86b94679803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='International Officers (click to expand)']/parent::*</value>
      <webElementGuid>f0086d5c-5731-4bf3-9911-566c9ea0664a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#collapseOfficers')]</value>
      <webElementGuid>2d67cc04-6b47-406c-85d7-0cdf9a5c9dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>ea9771b2-3f38-49d3-9ffb-ad05c8a3534c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'OfficerCollapse' and @href = '#collapseOfficers' and (text() = 'International Officers (click to expand)' or . = 'International Officers (click to expand)')]</value>
      <webElementGuid>d95d79b4-95f8-4b88-b27b-e6a864755053</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
