<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Instructions</name>
   <tag></tag>
   <elementGuidId>d495276d-8da0-4a5e-9aaf-a2ac997cf45c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = '#Instructions' and (text() = 'Instructions' or . = 'Instructions')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>61e20e25-70ef-4262-abec-a37c558bee6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Instructions</value>
      <webElementGuid>ef65397d-28f2-4e22-b659-d0029c792061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instructions</value>
      <webElementGuid>3aa7bab7-ca5f-490e-aca0-d70edbf2113b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/section[@class=&quot;clubSuccess proxySuccess myproxySuccess&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;clubSuccessTabs&quot;]/ul[@class=&quot;nav nav-pills&quot;]/li[2]/a[1]</value>
      <webElementGuid>5d6126b3-2ee8-405d-b8b7-6103cc84c3c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/section[2]/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>83b4319e-6703-44d1-964b-3477497890da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Instructions')]</value>
      <webElementGuid>8f802dda-feb1-42c3-85bc-845fbeba3ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Proxies'])[1]/following::a[1]</value>
      <webElementGuid>f7a09e79-760b-4e02-98d4-c504885c8bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note: Your Proxy Summary Report will be generated after you have accepted at least one vote.'])[1]/following::a[2]</value>
      <webElementGuid>49216fad-78a0-462a-8419-bfa5f7b7e5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2 votes)'])[1]/preceding::a[1]</value>
      <webElementGuid>41618ef5-d692-417c-a145-94c4b0816ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Instructions']/parent::*</value>
      <webElementGuid>e3169784-e1cc-4c20-b9d5-3c0d679460b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#Instructions')]</value>
      <webElementGuid>f9806324-0f81-4294-b991-19db2c8d1b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>9db1d7d1-4670-4290-9a62-6bee0538ec99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#Instructions' and (text() = 'Instructions' or . = 'Instructions')]</value>
      <webElementGuid>a09e814b-3deb-4f87-8b81-abd09942d17a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
