<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Proposals (click to expand)</name>
   <tag></tag>
   <elementGuidId>716c7177-d94f-4f26-9641-3e7fc88f266c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProposalsCollapse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ProposalsCollapse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6edcefcc-e842-466e-a5b8-e88a3e1d7c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>d71f392e-27c4-4a28-9b90-d212da406825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProposalsCollapse</value>
      <webElementGuid>931ccf1f-cd12-48bd-be6b-85a9b06c2abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordionassign</value>
      <webElementGuid>90526010-7880-4b48-bdc0-b3288ae06ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#collapseProposals</value>
      <webElementGuid>79ec1e25-c912-4fe3-a7d5-a259d76840bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1e1d8f22-3b18-4206-bc2e-77208d846f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proposals (click to expand)</value>
      <webElementGuid>310ce86b-3bbe-43c0-9ef7-6cfd3cb894f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProposalsCollapse&quot;)</value>
      <webElementGuid>99792d4b-d7a9-4a30-aaa6-65378a47cf12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ProposalsCollapse']</value>
      <webElementGuid>b42f0095-259d-410e-9e3e-c72116f1ee66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionassign']/div[3]/div/h3/a</value>
      <webElementGuid>5f9f423e-cbfc-4825-916e-4424c9900429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Proposals (click to expand)')]</value>
      <webElementGuid>7fcd5227-3125-4fd6-a0f6-92bbed2d4f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region 14'])[1]/following::a[3]</value>
      <webElementGuid>6bb250d8-b1cd-4818-ad47-235848466f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region 12'])[1]/following::a[4]</value>
      <webElementGuid>831a6ee6-0a74-4a65-b08f-727a9a582b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proposal A: Consistency and Clarity'])[1]/preceding::a[1]</value>
      <webElementGuid>9f84730f-8557-495b-9568-5857f05f8147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For'])[1]/preceding::a[1]</value>
      <webElementGuid>6d7c22d7-3335-462e-8c95-6ffc12e0ede1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proposals (click to expand)']/parent::*</value>
      <webElementGuid>b7c483dd-7977-40bd-b51d-d033b81f8099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#collapseProposals')]</value>
      <webElementGuid>3c4da0a2-d004-4e03-af41-46457ecd630e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h3/a</value>
      <webElementGuid>4c805645-7f7f-44b7-892c-c0e7a0008074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ProposalsCollapse' and @href = '#collapseProposals' and (text() = 'Proposals (click to expand)' or . = 'Proposals (click to expand)')]</value>
      <webElementGuid>fdc98338-d099-4fb5-b1cc-0e98939c0a28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
