<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Unaccepted (2 votes)</name>
   <tag></tag>
   <elementGuidId>1ebf3896-8b5d-4472-9174-b913b35a899f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UnacceptedCollapse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='UnacceptedCollapse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96b6f019-9157-442c-98f1-883f41825bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>84aa4d57-8c60-4b99-9b7c-0e07186243e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UnacceptedCollapse</value>
      <webElementGuid>eb355e80-fba0-4cbe-be7e-8d07b7611eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordionmyproxy</value>
      <webElementGuid>89e9f67e-5fe8-4bf3-965b-8af9c7966115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#collapseUnaccepted</value>
      <webElementGuid>4690eb48-dc28-48b8-b057-54f4dcd0ca65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b2e637f9-2b0f-42c1-b0b6-d0b10caf2424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-collapse collapse in collapsed</value>
      <webElementGuid>536d2bd0-646b-42f0-b14c-219dde53ac8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unaccepted (2 votes)</value>
      <webElementGuid>b481fc73-f658-420f-a89d-bf59655be78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UnacceptedCollapse&quot;)</value>
      <webElementGuid>c893490a-8ac6-48c6-b657-051f7c9005ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='UnacceptedCollapse']</value>
      <webElementGuid>220f9c01-2773-4ccc-84b7-00cbe598b53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionmyproxy']/div/div/h3/a</value>
      <webElementGuid>4d73885c-5c77-4921-b55e-83b0df640217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instructions'])[1]/following::a[1]</value>
      <webElementGuid>12d57288-b6e9-4448-b708-005dde853e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Proxies'])[1]/following::a[2]</value>
      <webElementGuid>5567b57a-bad5-48b4-bb2d-f397fb86ee2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saturday, August 13, 2022'])[1]/preceding::a[1]</value>
      <webElementGuid>02fd6a6a-8d22-40a2-aae7-6f900eaf86e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unaccepted']/parent::*</value>
      <webElementGuid>307c946f-1645-4f44-a7c7-39da4cc6426c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#collapseUnaccepted')]</value>
      <webElementGuid>83b53911-ce34-4190-a745-f5c53e0250ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>2ad615f1-2a3a-44e9-a504-6d30d728f6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'UnacceptedCollapse' and @href = '#collapseUnaccepted' and (text() = 'Unaccepted (2 votes)' or . = 'Unaccepted (2 votes)')]</value>
      <webElementGuid>6267eb6c-fc06-4fc3-9f1f-f2ade2717869</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
