<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vote_InterDirector_Region6_2_vote1</name>
   <tag></tag>
   <elementGuidId>7a4659c9-c2d1-4c84-bf32-c5348224c3d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Region_6&quot;]//div[@data-candidateid=&quot;108&quot;]//*[@class=&quot;votingcardvotes&quot;]//*[@id=&quot;img1_2_46_108_1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
