<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vote_InterDirector_Region8_2_vote1</name>
   <tag></tag>
   <elementGuidId>73d06505-f7fc-4c05-aff1-e9844c3b87c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Region_8&quot;]//div[@data-candidateid=&quot;111&quot;]//*[@class=&quot;votingcardvotes&quot;]//*[@id=&quot;img1_2_47_111_1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
