<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vote_InterDirector_Region4_1_vote1</name>
   <tag></tag>
   <elementGuidId>404351a9-da24-4ae8-bbd6-9f0deb0bca48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Region_4&quot;]//div[@data-candidateid=&quot;105&quot;]//*[@class=&quot;votingcardvotes&quot;]//*[@id=&quot;img1_2_45_105_1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
