<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vote_InterDirector_Region4_2_vote1</name>
   <tag></tag>
   <elementGuidId>dc60baf5-6e13-4337-96de-efff8101726c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Region_4&quot;]//div[@data-candidateid=&quot;106&quot;]//*[@class=&quot;votingcardvotes&quot;]//*[@id=&quot;img1_2_45_106_1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
