<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vote_InterDirector_Region10_3_vote2</name>
   <tag></tag>
   <elementGuidId>4815e167-3a7c-4945-b70f-98b1a10c3eb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Region_10&quot;]//div[@data-candidateid=&quot;114&quot;]//*[@class=&quot;votingcardvotes&quot;]//*[@id=&quot;img2_2_48_114_2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
