<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vote_InterDirector_Region4_2_vote2</name>
   <tag></tag>
   <elementGuidId>4b6377a6-8073-441d-a6bd-7282823fc955</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Region_4&quot;]//div[@data-candidateid=&quot;106&quot;]//*[@class=&quot;votingcardvotes&quot;]//*[@id=&quot;img2_2_45_106_2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
