<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vote_InterDirector_Region12_1_vote1</name>
   <tag></tag>
   <elementGuidId>5d9449d7-7183-476e-a0f0-ad627d423ce4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Region_12&quot;]//div[@data-candidateid=&quot;115&quot;]//*[@class=&quot;votingcardvotes&quot;]//*[@id=&quot;img1_2_49_115_1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
