<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vote_InterDirector_Region8_1_vote1</name>
   <tag></tag>
   <elementGuidId>3ba5c0e8-63a2-4fcc-92dc-d0ff03b1618d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Region_8&quot;]//div[@data-candidateid=&quot;110&quot;]//*[@class=&quot;votingcardvotes&quot;]//*[@id=&quot;img1_2_47_110_1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
