<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_ClubID</name>
   <tag></tag>
   <elementGuidId>739f4c01-f7bb-4b5c-b5aa-b0aca1dc7101</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/main/div[1]/div[2]/div[3]/div/div[1]/table/thead/tr/th[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;tablesaw-3524&quot;]/thead/tr/th[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;tablesaw-3524&quot;]/thead/tr/th[1]/button</value>
   </webElementXpaths>
</WebElementEntity>
